"""
MAIA Beacon Setup Module
Clones/updates MAIA Beacon repository, installs Python dependencies,
and generates the .env configuration file for the beacon.
"""

import sys
from pathlib import Path
from configs import load_config, ROOT_DIR
from llama_setup import ensure_git_repo, run_cmd


def ensure_beacon_deps(beacon_dir):
    """Install Python requirements for MAIA-Beacon."""
    req_file = Path(beacon_dir) / "requirements.txt"
    if req_file.exists():
        print(f"[+] Installing MAIA-Beacon dependencies from {req_file}...")
        run_cmd([sys.executable, "-m", "pip", "install", "-r", str(req_file)])


def configure_beacon_env(beacon_dir, llama_exe, config):
    """Generate .env file for MAIA-Beacon."""
    beacon_path = Path(beacon_dir).resolve()
    models_path = (ROOT_DIR / config["models_dir"]).resolve()
    models_path.mkdir(parents=True, exist_ok=True)

    llama_exe_str = str(Path(llama_exe).resolve()) if llama_exe else ""
    env_file = beacon_path / ".env"
    env_content = f"""# Auto-generated by MAIA Beacon setup bootstrapper
BEACON_HOST={config['beacon_host']}
BEACON_PORT={config['beacon_port']}
LLAMA_SERVER_EXE={llama_exe_str}
MODELS_DIR={str(models_path)}
TARGET_DEVICE=AUTO
IDLE_TIMEOUT_SECONDS={config['idle_timeout_seconds']}
"""
    with open(env_file, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"[+] Generated MAIA-Beacon configuration file: {env_file}")
    return env_file


def setup_maia(llama_exe_path=None):
    """
    Setup MAIA Beacon repository, dependencies, and environment configuration.
    Returns Path to MAIA-Beacon directory.
    """
    config = load_config()
    deps_dir = ROOT_DIR / config["deps_dir"]
    beacon_dir = deps_dir / "MAIA-Beacon"

    # Ensure Git repository cloned at configured tag
    ensure_git_repo(
        repo_url=config["beacon_repo"],
        target_dir=beacon_dir,
        tag=config.get("beacon_tag", "v1.0.0")
    )

    # Install Python dependencies
    ensure_beacon_deps(beacon_dir)

    # Write .env configuration file
    configure_beacon_env(beacon_dir, llama_exe_path, config)

    print(f"[OK] MAIA Beacon setup completed: {beacon_dir}")
    return beacon_dir


if __name__ == "__main__":
    setup_maia()
